2023-06-25 14:34:12 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:34:12 - INFO - Added job "job" to job store "default"
2023-06-25 14:34:12 - INFO - Scheduler started
2023-06-25 14:34:12 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:34:12 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:34:12 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:34:12 - WARNING - Updates were skipped successfully.
2023-06-25 14:34:12 - INFO - Start polling.
2023-06-25 14:34:14 - INFO - User action: /joke (User ID: 6013011895)
2023-06-25 14:35:31 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:35:31 - INFO - Added job "job" to job store "default"
2023-06-25 14:35:31 - INFO - Scheduler started
2023-06-25 14:35:31 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:35:31 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:35:31 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:35:31 - WARNING - Updates were skipped successfully.
2023-06-25 14:35:32 - INFO - Start polling.
2023-06-25 14:36:33 - INFO - Stop polling...
2023-06-25 14:36:33 - WARNING - Goodbye!
2023-06-25 14:36:58 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:36:58 - INFO - Added job "job" to job store "default"
2023-06-25 14:36:58 - INFO - Scheduler started
2023-06-25 14:36:58 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:36:58 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:36:58 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:36:58 - WARNING - Updates were skipped successfully.
2023-06-25 14:36:58 - INFO - Start polling.
2023-06-25 14:39:00 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:39:00 - INFO - Added job "job" to job store "default"
2023-06-25 14:39:00 - INFO - Scheduler started
2023-06-25 14:39:00 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:39:00 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:39:00 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:39:00 - WARNING - Updates were skipped successfully.
2023-06-25 14:39:00 - INFO - Start polling.
2023-06-25 14:39:57 - INFO - User action: /start (User ID: 6013011895)
2023-06-25 14:40:18 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:40:18 - INFO - Added job "job" to job store "default"
2023-06-25 14:40:18 - INFO - Scheduler started
2023-06-25 14:40:18 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:40:18 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:40:18 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:40:18 - WARNING - Updates were skipped successfully.
2023-06-25 14:40:18 - INFO - Start polling.
2023-06-25 14:41:13 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:41:13 - INFO - Added job "job" to job store "default"
2023-06-25 14:41:13 - INFO - Scheduler started
2023-06-25 14:41:13 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:41:13 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:41:13 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:41:13 - WARNING - Updates were skipped successfully.
2023-06-25 14:41:14 - INFO - Start polling.
2023-06-25 14:41:55 - INFO - User action: Bot added to group (Group name: Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики)
2023-06-25 14:46:16 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:46:16 - INFO - Added job "job" to job store "default"
2023-06-25 14:46:16 - INFO - Scheduler started
2023-06-25 14:46:16 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:46:16 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:46:16 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:46:16 - WARNING - Updates were skipped successfully.
2023-06-25 14:46:16 - INFO - Start polling.
2023-06-25 14:46:33 - ERROR - Update: {"update_id": 247832470, "message": {"message_id": 161, "from": {"id": 5617952282, "is_bot": false, "first_name": "Nobody", "username": "mak2r", "language_code": "uk"}, "chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "date": 1687704393, "new_chat_participant": {"id": 5617952282, "is_bot": false, "first_name": "Nobody", "username": "mak2r", "language_code": "uk"}, "new_chat_member": {"id": 5617952282, "is_bot": false, "first_name": "Nobody", "username": "mak2r", "language_code": "uk"}, "new_chat_members": [{"id": 5617952282, "is_bot": false, "first_name": "Nobody", "username": "mak2r", "language_code": "uk"}]}}
Exception: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:46:33 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'Message' object has no attribute 'new_chat_member'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 36, in bot_added_to_chat
    if event.new_chat_member.user.id == bot_id:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:47:02 - ERROR - Update: {"update_id": 247832474, "message": {"message_id": 163, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "date": 1687704421, "new_chat_participant": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_member": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_members": [{"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}]}}
Exception: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:47:02 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-28' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'Message' object has no attribute 'new_chat_member'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 36, in bot_added_to_chat
    if event.new_chat_member.user.id == bot_id:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:48:05 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:48:05 - INFO - Added job "job" to job store "default"
2023-06-25 14:48:05 - INFO - Scheduler started
2023-06-25 14:48:05 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:48:05 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:48:05 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:48:05 - WARNING - Updates were skipped successfully.
2023-06-25 14:48:05 - INFO - Start polling.
2023-06-25 14:49:25 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:49:25 - INFO - Added job "job" to job store "default"
2023-06-25 14:49:25 - INFO - Scheduler started
2023-06-25 14:49:25 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:49:25 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:49:25 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:49:25 - WARNING - Updates were skipped successfully.
2023-06-25 14:49:26 - INFO - Start polling.
2023-06-25 14:49:39 - ERROR - Update: {"update_id": 247832482, "message": {"message_id": 167, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "date": 1687704579, "new_chat_participant": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_member": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_members": [{"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}]}}
Exception: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:49:39 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'Message' object has no attribute 'new_chat_member'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 36, in bot_added_to_chat
    for new_member in event.new_chat_member:
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:50:56 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:50:56 - INFO - Added job "job" to job store "default"
2023-06-25 14:50:56 - INFO - Scheduler started
2023-06-25 14:50:56 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:50:56 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:50:57 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:50:57 - WARNING - Updates were skipped successfully.
2023-06-25 14:50:57 - INFO - Start polling.
2023-06-25 14:52:20 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:52:20 - INFO - Added job "job" to job store "default"
2023-06-25 14:52:20 - INFO - Scheduler started
2023-06-25 14:52:20 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:52:20 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:52:20 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:52:20 - WARNING - Updates were skipped successfully.
2023-06-25 14:52:20 - INFO - Start polling.
2023-06-25 14:52:34 - ERROR - Update: {"update_id": 247832490, "message": {"message_id": 171, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "date": 1687704754, "new_chat_participant": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_member": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_members": [{"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}]}}
Exception: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:52:34 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'Message' object has no attribute 'new_chat_member'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    if event.from_user.id == event.new_chat_member:
                             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'new_chat_member'
2023-06-25 14:56:58 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 14:56:58 - INFO - Added job "job" to job store "default"
2023-06-25 14:56:58 - INFO - Scheduler started
2023-06-25 14:56:58 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 14:56:58 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 14:56:58 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 14:56:58 - WARNING - Updates were skipped successfully.
2023-06-25 14:56:58 - INFO - Start polling.
2023-06-25 14:57:07 - INFO - User action: Bot added to group(Group name: Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики)
2023-06-25 14:57:30 - INFO - User action: Bot added to group(Group name: Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики)
2023-06-25 15:01:21 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:01:21 - INFO - Added job "job" to job store "default"
2023-06-25 15:01:21 - INFO - Scheduler started
2023-06-25 15:01:21 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:01:21 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:01:21 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:01:21 - WARNING - Updates were skipped successfully.
2023-06-25 15:01:21 - INFO - Start polling.
2023-06-25 15:01:37 - ERROR - Update: {"update_id": 247832500, "message": {"message_id": 179, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "date": 1687705297, "new_chat_participant": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_member": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "new_chat_members": [{"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}]}}
Exception: 'Message' object has no attribute 'new_chat_member'
2023-06-25 15:01:37 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'Message' object has no attribute 'new_chat_member'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    if bot_id == event.new_chat_member.user.id:
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'new_chat_member'
2023-06-25 15:05:10 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:05:10 - INFO - Added job "job" to job store "default"
2023-06-25 15:05:10 - INFO - Scheduler started
2023-06-25 15:05:10 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:05:10 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:05:10 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:05:10 - WARNING - Updates were skipped successfully.
2023-06-25 15:05:10 - INFO - Start polling.
2023-06-25 15:05:39 - ERROR - Update: {"update_id": 247832503, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705539, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:05:39 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 36, in bot_added_to_chat
    for new_member in event.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:05:44 - ERROR - Update: {"update_id": 247832505, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705544, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:05:44 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-24' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 36, in bot_added_to_chat
    for new_member in event.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:07:14 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:07:14 - INFO - Added job "job" to job store "default"
2023-06-25 15:07:14 - INFO - Scheduler started
2023-06-25 15:07:14 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:07:14 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:07:14 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:07:14 - WARNING - Updates were skipped successfully.
2023-06-25 15:07:14 - INFO - Start polling.
2023-06-25 15:07:19 - ERROR - Update: {"update_id": 247832507, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705638, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:07:19 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    for new_member in message.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:07:27 - ERROR - Update: {"update_id": 247832509, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705647, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:07:27 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    for new_member in message.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:08:14 - ERROR - Update: {"update_id": 247832511, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705694, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:08:14 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-27' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    for new_member in message.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:08:20 - ERROR - Update: {"update_id": 247832513, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705700, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:08:20 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-34' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    for new_member in message.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:09:42 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:09:42 - INFO - Added job "job" to job store "default"
2023-06-25 15:09:42 - INFO - Scheduler started
2023-06-25 15:09:42 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:09:42 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:09:42 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:09:42 - WARNING - Updates were skipped successfully.
2023-06-25 15:09:42 - INFO - Start polling.
2023-06-25 15:10:56 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:10:56 - INFO - Added job "job" to job store "default"
2023-06-25 15:10:56 - INFO - Scheduler started
2023-06-25 15:10:56 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:10:56 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:10:56 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:10:56 - WARNING - Updates were skipped successfully.
2023-06-25 15:10:56 - INFO - Start polling.
2023-06-25 15:11:04 - ERROR - Update: {"update_id": 247832519, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705864, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:11:04 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    for new_member in message.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:11:09 - ERROR - Update: {"update_id": 247832521, "my_chat_member": {"chat": {"id": -1001944644214, "title": "Mak5er, \u722a\uff91\u049c\u4e02\u4e47\u5c3a™ та Анекдотики", "username": "dfhdfgfdh23", "type": "supergroup"}, "from": {"id": 6013011895, "is_bot": false, "first_name": "Mak5er", "username": "mak5er", "language_code": "uk"}, "date": 1687705869, "old_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "left"}, "new_chat_member": {"user": {"id": 6293095869, "is_bot": true, "first_name": "Анекдотики", "username": "makser_humor_bot"}, "status": "member"}}}
Exception: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:11:09 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'ChatMemberUpdated' object has no attribute 'new_chat_members'")>
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 302, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\handlers\user.py", line 35, in bot_added_to_chat
    for new_member in message.new_chat_members:
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMemberUpdated' object has no attribute 'new_chat_members'
2023-06-25 15:12:08 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:12:08 - INFO - Added job "job" to job store "default"
2023-06-25 15:12:08 - INFO - Scheduler started
2023-06-25 15:12:08 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:12:08 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:12:09 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:12:09 - WARNING - Updates were skipped successfully.
2023-06-25 15:12:09 - INFO - Start polling.
2023-06-25 15:13:38 - INFO - Stop polling...
2023-06-25 15:13:38 - WARNING - Goodbye!
2023-06-25 15:13:48 - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\bot\api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2702)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Joke Bot 2.0\venv\Lib\site-packages\aiogram\bot\api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2702)
2023-06-25 15:13:53 - WARNING - Polling is stopped.
2023-06-25 15:14:15 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:14:15 - INFO - Added job "job" to job store "default"
2023-06-25 15:14:15 - INFO - Scheduler started
2023-06-25 15:14:15 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:14:15 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:14:15 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:14:15 - WARNING - Updates were skipped successfully.
2023-06-25 15:14:15 - INFO - Start polling.
2023-06-25 15:15:22 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:15:22 - INFO - Added job "job" to job store "default"
2023-06-25 15:15:22 - INFO - Scheduler started
2023-06-25 15:15:22 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:15:22 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:15:22 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:15:22 - WARNING - Updates were skipped successfully.
2023-06-25 15:15:23 - INFO - Start polling.
2023-06-25 15:20:29 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-06-25 15:20:29 - INFO - Added job "job" to job store "default"
2023-06-25 15:20:29 - INFO - Scheduler started
2023-06-25 15:20:29 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.50.64:8080
2023-06-25 15:20:29 - INFO - [33mPress CTRL+C to quit[0m
2023-06-25 15:20:29 - INFO - Bot: Анекдотики [@makser_humor_bot]
2023-06-25 15:20:29 - WARNING - Updates were skipped successfully.
2023-06-25 15:20:29 - INFO - Start polling.
2023-06-25 15:21:09 - INFO - Stop polling...
2023-06-25 15:21:09 - WARNING - Goodbye!
